name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - name: Install apt dependencies
      run: sudo apt-get install build-essential python3-pip cmake gobject-introspection-dev libglib2.0-dev ninja-build gjs
    - name: Install pip dependencies
      run: sudo pip3 install meson

    - name: Clone jasmine-gjs
      uses: actions/checkout@v3
      with:
        path: jasmine-gjs
        repository: ptomato/jasmine-gjs

    - name: Configure jasmine-gjs
      run: cd jasmine-gjs && meson build && cd build && ninja && sudo ninja install

    - name: Clone ggml
      uses: actions/checkout@v3
      with:
        path: ggml
        repository: ggerganov/ggml

    - name: Build ggml
      uses: threeal/cmake-action@v1.2.0
      with:
        generator: ninja
        source-dir: ggml
        build-dir: ggml/build
        run-build: true
        options: -DCMAKE_INSTALL_PREFIX=/usr

    - name: Install ggml
      run: cd ggml/build && sudo ninja install

    - uses: actions/checkout@v3
    - name: Meson Build
      # You may pin to the exact commit or the version.
      # uses: BSFishy/meson-build@656b2a360964b249ac82905a52018921e01d875b
      uses: BSFishy/meson-build@v1.0.3
      with:
        # The action to run
        action: build
        # The directory to build the project to
        directory: build # default is build
